
general:
    visualize: false # (true, false) Weather or not the local visuilization GUI shoud run to display detections and the real time depth map
    camera_config: "ZED2_camera_settings.yaml" # (File Path) The file path to the camera config yaml which contains the approprate camera video settings
    inference_config: "models/2025/frc2025v1.yaml" # (File Path) The file path to the inference config yaml which contains the settings for the YOLO object detector runtime

# All settings related to the ZED's stereo depth functionality
depth: 
    mode: "NEURAL_LIGHT" # (NEURAL_LIGHT, NEURAL, NEURAL_PLUS) The method used for stero depth extraction, listed in assending qulity and resource demand
    stabilization: 0 # (0-100) Controls the degree to which a linear filter is applyed to depth data to compensate for measurment oscilations. 0 disables smoothing
    depth_conf_thresh: 100 # (1-100) Threshold to reject depth values based on their confidence. Decreasing this value will remove depth data from both objects edges and low textured areas, to keep only confident depth estimation data. 
    texture_conf_thresh: 100 # (1-100) Threshold to reject depth values based on their texture confidence. Decreasing this value will remove depth data from image areas which are uniform. 
    remove_saturated_areas: false # Weather or not areas with a saturaton of 255 should be removed from depth calculations due to a lack of any detail
    max_dist: 20.0 #The maximum distance the ZED will calculate depth data for
    min_dist: -1 #The minimum distance the ZED will calculate depth data for, -1 set this value to the default

# All settings relatated to the ZED's NT interactions
networktables:
    publish: true # If this programme shoud publish detection data to NT
    team: 5104 # The team number of the NT server
    name: "ZED" # The name of the NT client and main table

# All settings related to the ZED's VIO/SLAM abilities
localization:
    area_memory: false # If the ZED shoud map its suroundings during operation to improve localization accuracy, slight perfomance hit
    pose_smoothing: true # If the ZED shoud smooth out the sudden pose change caused by loop closure when in SLAM mode
    use_gravity_origin: true # If the ZED should use the direction of gravity to estimate its angle relitive to the ground, only effects world reletive values like pose
    min_depth: -1 # The minimum depth of pixles to be used in VIO caclulations, helps ignore fixed obstructuions in your view frame like robot parts
    mode: "GEN1" # (GEN1, GEN2) The type of pose estimation to be used, GEN2 performs better but has more of a performance demand

visualization:
    desktop:
        ocv_2d: false # If the 2D OpenCV bounding box and overhead views shoud be shown on the desktop
        point_cloud_3d: false # If the 3D point cloud render and 3D object bounding boxes shoud be shown on the desktop
    webserver:
        enable: false # If the flask webserver which livestream's the OpenCV visulization to the configured host and port shoud run
        host: '0.0.0.0' # The IP address the webserer shoud stream to
        port: 5000 # The port the webserver should stream to
        ocv_backend: false # If the 2D OpenCV bounding box and overhead views should be rendered to the livestream
        
    
