
general:
    visualize: true # (true, false) Weather or not the local visuilization GUI shoud run to display detections and the real time depth map
    camera_config: "ZED2_camera_settings.yaml" # (File Path) The file path to the camera config yaml which contains the approprate camera video settings
    inference_config: "models/2024/frc2024no_YOLOv10n/frc2024no_YOLOv10n.yaml" # (File Path) The file path to the inference config yaml which contains the settings for the YOLO object detector runtime

# All settings related to the ZED's stereo depth functionality
depth: 
    mode: PERFORMANCE # (PERFORMANCE, QUALITY, ULTRA, NEURAL, NEURAL_PLUS) The method used for stero depth extraction, listed in assending qulity and resource demand
    stabilization: 0 # (0-100) Controls the degree to which a linear filter is applyed to depth data to compensate for measurment oscilations. 0 disables smoothing
    depth_conf_thresh: 100 # (1-100) Threshold to reject depth values based on their confidence. Decreasing this value will remove depth data from both objects edges and low textured areas, to keep only confident depth estimation data. 
    texture_conf_thresh: 100 # (1-100) Threshold to reject depth values based on their texture confidence. Decreasing this value will remove depth data from image areas which are uniform. 
    remove_saturated_areas: true # Weather or not areas with a saturaton of 255 should be removed from depth calculations due to a lack of any detail
    max_dist: 20.0 #The maximum
    min_dist: -1

networktables:
    publish: true
    team: 5104
    name: ZED

localization:
    area_memory: true
    pose_smoothing: false
    use_gravity_origin: true
    min_depth: -1
    mode: GEN1

visualization:
    desktop:
        ocv_2d: false
        point_cloud_3d: false
    webserver:
        enable: false
        host: '127.0.0.1'
        port: 5000
        
    
